logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    com.wokoworks: DEBUG
  pattern:
    console: "%date{yy-MM-dd HH:mm:ss.SSS} %5p ${PID:-} --- [%15.15t] %-40.40logger{39}[%4line]: %msg%n"


spring:
  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    username: wokoworks
    url: jdbc:mysql://127.0.0.1/test?characterEncodeing=utf-8&useSSL=false&serverTimezone=GMT%2b8
  #  # spring模板引擎thymeleaf配置
  #  thymeleaf:
  #    cache: false
  #    prefix: classpath:/templates/
  #    suffix: .html
  #    encoding: UTF-8
  #    mode: HTML5
  # jpa配置
  jpa:
    show-sql: true
  #redis服务器地址
  redis:
    host: redis
    port: 6379
    password: wokoworks
    timeout: 5000
    lettuce:
      pool:
        max-active: 100
        max-idle: 100
        min-idle: 10
        max-wait: 1000
